# Configuration for object detection node
/object_det:
  ros__parameters:
    # print debug output
    debug: true
    # image source topic
    topic: "/background/color_small_416"
    print_detections: false
    print_fps: true
    det_topic: "/object_det/objects"
    fps_topic: "/object_det/fps"
    max_fps: 30.0
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5

    ### --------------- ###
    # YOLO STUFF
    #(Valid DLA-Cores: 0 or 1) -1 disables the usage of DLAs
    DLA_CORE: -1
    # Use 16-Bit floating point units (this is automatically enabled when DLAs are used)
    USE_FP16: true
    ONNX_FILE: "/opt/dev/DL_Models/yolo_object/model/yolov4-416.onnx"
    # If the engine file is not present the engine is build
    ENGINE_FILE: "/opt/dev/engines/yolov4-416_dla0.engine"
    CLASS_FILE: "/opt/dev/DL_Models/yolo_object/model/coco.names"
    DETECT_STR: "DETECTED_OBJECTS"
    AMOUNT_STR: "DETECTED_OBJECTS_AMOUNT"
    FPS_STR: "OBJECT_DET_FPS"
    YOLO_THRESHOLD: 0.25



# Configuration for gesture detection node
/gesture_det:
  ros__parameters:
    # print debug output
    debug: true
    # image source topic
    topic: "/background/color_small_full_640_kar"
    print_detections: false
    print_fps: true
    det_topic: "/gesture_det/gestures"
    fps_topic: "/gesture_det/fps"
    max_fps: 30.0
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5

    ### --------------- ###
    # YOLO STUFF
      #(Valid DLA-Cores: 0 or 1) -1 disables the usage of DLAs
    DLA_CORE: -1
    # Use 16-Bit floating point units (this is automatically enabled when DLAs are used)
    USE_FP16: true
    ONNX_FILE: "/opt/dev/DL_Models/yolo_human/model/yolov7-tiny-hand-nms.onnx"
    # If the engine file is not present the engine is build
    ENGINE_FILE: "/opt/dev/engines/yolov7-tiny-hand-nms-dla-1.engine"
    CLASS_FILE: "/opt/dev/DL_Models/yolo_human/data/hand_set.names"

    DETECT_STR: "DETECTED_GESTURES"
    AMOUNT_STR: "DETECTED_GESTURES_AMOUNT"
    FPS_STR: "GESTURE_DET_FPS"

    YOLO_THRESHOLD: 0.25

    
